name: Cypress Tests and Report test 1234534

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          npm install cypress --save-dev

      - name: Install Cypress binary
        run: npx cypress install

      - name: Run Cypress tests and generate report
        run: npm run cypress:run

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Cypress-Artifacts
          path: |
            cypress/reports/**
            cypress/screenshots/**
            cypress/videos/**
