name: Dispatch Cypress Run

on:
  push:
    branches:
      - main  

jobs:
  trigger-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch Event
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/<username>/<repoA>/dispatches \
               -d '{"event_type":"run-cypress-tests"}'
